---
# tasks file for pgsql
- name: Creates directory /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: PostgreSQL repo | add key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/apt.postgresql.org.asc
    mode: "0755"

- name: PostgreSQL repo | add source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/apt.postgresql.org.asc] \
     https://apt.postgresql.org/pub/repos/apt \
     {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true

- name: "Install PostgreSQL {{ pgsql_version }}"
  ansible.builtin.apt:
    name:
      - "postgresql-{{ pgsql_version }}"
      - "postgresql-contrib-{{ pgsql_version }}"
      - libpq-dev
      - python3-psycopg2
    state: present

- name: Postgresql is started and enabled at boot
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
