---
- name: Uninstall old packages docker-*
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  when:
    common_docker_remove_old_version

- name: Creates directory /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Docker repo | add key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0755"

- name: Docker repo | add source
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ [ansible_architecture] | map('extract', common_deb_architecture) | first }} signed-by=/etc/apt/keyrings/docker.asc] \
     https://download.docker.com/linux/{{ ansible_distribution | lower }} \
     {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install packages from docker-*
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Configure docker
  ansible.builtin.include_tasks: "docker_config.yml"
